version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/project
permissions:
  - object: /home/ec2-user/project
    pattern: "**"
    owner: root
    group: root
    mode: 755
hooks:
  ApplicationStart:
    - location: /start.sh
      timeout: 700
      runas: root